document.addEventListener("DOMContentLoaded", function() {
    var submitButton = document.getElementById("submitBtn");
    var descriptionPage = document.getElementById("descriptionPage");
    var descriptionContainer = document.getElementById("description");

    submitButton.addEventListener("click", function() {
        var selectedCountry = document.getElementById("countries").value;
        var descriptionText = getDescription(selectedCountry);
        descriptionContainer.innerHTML = descriptionText;
        descriptionPage.style.display = "block";
    });

    function getDescription(country) {
        switch (country) {
            case "Afghanistan":
                return "<div><strong>Fraxinus sogdiana</strong></div><div><img src='afganisthan_plant.jpg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Fraxinus sogdiana, commonly known as the Sogdian ash, is a species of flowering plant in the olive family, Oleaceae, native to Central Asia, particularly Afghanistan, Tajikistan, and Uzbekistan. This deciduous tree is valued for its ornamental beauty and its use in traditional medicine. It typically grows up to 15 meters tall and has distinctive compound leaves with serrated edges.</p><p>In Afghanistan, Fraxinus sogdiana plays a significant ecological and cultural role. Its wood is highly valued for various purposes, including furniture making, tool handles, and construction. Moreover, in traditional Afghan medicine, different parts of the tree, such as the bark and leaves, are used to treat ailments ranging from fever to digestive issues.</p><p>Due to habitat loss and overexploitation, the Sogdian ash faces threats in its native range. Conservation efforts are underway to protect its natural habitats and promote sustainable harvesting practices.</p><p><a href='https://www.bing.com/ck/a?!&&p=97fdffb340f10f1bJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTMzNQ&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=fraxinus+sogdiana+in+afganisthan&u=a1aHR0cHM6Ly93d3cucmVzZWFyY2hzcXVhcmUuY29tL2FydGljbGUvcnMtMTUwOTgyNi92MQ&ntb=1' target='_blank'>Know More</a></p></div>";
            case "Algeria":
                return "<div><strong>Algerian silver fir</strong></div><div><img src='algeria_plants.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>The Algerian silver fir, scientifically known as Abies numidica, is a species of fir tree endemic to the mountainous regions of Algeria in North Africa. This coniferous tree is highly valued for its timber and plays a crucial role in the ecosystems where it occurs.</p><p>Algerian silver fir is known for its distinctive silver-gray bark and dark green needles arranged spirally on the branches. It typically grows at high elevations, often above 1,000 meters, in the Kabylie region and other mountain ranges in northern Algeria.</p><p>The timber of the Algerian silver fir is prized for its quality and is used in construction, carpentry, and furniture making. However, like many other tree species, it faces threats from habitat loss, overexploitation, and climate change.</p><p><a href='https://www.bing.com/ck/a?!&&p=8a563dc9fc9ec51eJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTI1OA&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=algerian+silver+fir&u=a1aHR0cHM6Ly93d3cuZXVmb3JnZW4ub3JnL3NwZWNpZXMvYWJpZXMtbnVtaWRpY2Ev&ntb=1' target='_blank'>Know More</a></p></div>";
            
            case "Argentina":
                return "<div><strong>Acacia caven</strong></div><div><img src='argentina.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Acacia caven, commonly known as 'espinillo' or 'caven,' is a species of flowering tree native to South America, particularly found in Argentina, Chile, Uruguay, and southern Brazil. It belongs to the Fabaceae family, which is the pea family.</p><p>This tree species is characterized by its small, yellow flowers and its thorny branches. It typically grows in dry or semi-arid regions, including savannas, shrublands, and along riverbanks.</p><p>Acacia caven plays a significant ecological role, providing habitat and food for various wildlife species. It also has cultural significance and is used in traditional medicine and woodworking. Additionally, its wood is used for fuel, charcoal production, and construction.</p><p><a href='https://www.bing.com/ck/a?!&&p=b637f91c64eb02b2JmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTMwOQ&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=acacia+etilis&u=a1aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvQWNhY2lhX2V4aWxpcw&ntb=1' target='_blank'>Know More</a></p></div>";
            case "Austria":
                return "<div><strong>Orthotrichum scanicum</strong></div><div><img src='austria.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Orthotrichum scanicum is a species of moss belonging to the genus Orthotrichum. Mosses are small, non-vascular plants that typically grow in dense clumps or mats in damp environments.</p><p>Orthotrichum scanicum is known for its distinctive appearance, characterized by small, densely packed leaves and a creeping growth habit. It is commonly found growing on rocks, tree trunks, and other surfaces in moist, shaded areas, such as forests and stream banks.</p><p>While Orthotrichum scanicum itself may not be of significant economic or cultural importance, it contributes to the overall biodiversity and ecological health of the ecosystems in which it occurs. Monitoring and conservation efforts aimed at preserving moss diversity, including Orthotrichum scanicum, are important for maintaining healthy ecosystems in Austria and beyond.</p><p><a href='https://www.bing.com/ck/a?!&&p=1e472d7e9010e1f4JmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTMzNg&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=orthotrichum+scanicum&u=a1aHR0cHM6Ly93d3cudGFuZGZvbmxpbmUuY29tL2RvaS9hYnMvMTAuMTE3OS8xNzQzMjgyMDlYNDA0OTM0&ntb=1' target='_blank'>Know More</a></p></div>";

            case "Bangladesh":
                return "<div><strong>Aglaia perviridis</strong></div><div><img src='bangladesh.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Aglaia perviridis is a species of flowering plant in the Meliaceae family, native to Southeast Asia, including Bangladesh. Commonly known as 'Harikanta' in Bengali, it is a small to medium-sized evergreen tree.</p><p>This tree species is valued for various purposes in Bangladesh. Its wood is used in construction and carpentry, while its bark and leaves are utilized in traditional medicine for their purported medicinal properties. Additionally, Aglaia perviridis has cultural significance and is sometimes planted for ornamental purposes in gardens and parks.</p><p>In its natural habitat, Aglaia perviridis contributes to the biodiversity and ecological balance of forests and woodlands. However, like many other tree species, it faces threats from deforestation, habitat degradation, and overexploitation.</p><p><a href='https://www.bing.com/ck/a?!&&p=53ecd0466291c7abJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTM2Nw&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=aglaia+perviridis&u=a1aHR0cHM6Ly93d3cuc2NpZW5jZWRpcmVjdC5jb20vc2NpZW5jZS9hcnRpY2xlL3BpaS9TMDAzMTk0MjIyMDMxMTU1OQ&ntb=1' target='_blank'>Know More</a></p></div>";
            
            case "Bhutan":
                return "<div><strong>Bazzania bhutanica</strong></div><div><img src='bhutan.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Bazzania bhutanica is a species of liverwort, a type of non-vascular plant belonging to the family Lepidoziaceae. Liverworts are small, herbaceous plants that typically grow in moist and shaded habitats, often forming dense mats on the forest floor, rocks, or tree trunks.</p><p>This particular species, Bazzania bhutanica, is named after the country where it was discovered, Bhutan. It is endemic to Bhutan, meaning it is found nowhere else in the world. Liverworts like Bazzania bhutanica play important ecological roles, such as soil stabilization, nutrient cycling, and providing habitat for microorganisms and small invertebrates.</p><p>Conservation efforts in Bhutan aim to protect the diverse flora and fauna, including rare and endemic species like Bazzania bhutanica. This includes establishing protected areas, conducting research on biodiversity, and promoting sustainable land management practices to ensure the long-term survival of Bhutan's unique ecosystems.</p><p><a href='https://www.bing.com/ck/a?!&&p=1d179fd899c71ddfJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTI0OA&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=bazzania+bhutanica&u=a1aHR0cHM6Ly9iaW9vbmUub3JnL2pvdXJuYWxzL2xpbmRiZXJnaWEvdm9sdW1lLTM3L2lzc3VlLTIvbGluYmcuMDEwNDkvQmF6emFuaWEtYmh1dGFuaWNhLUxlcGlkb3ppYWNlYWUtTWFyY2hhbnRpb3BoeXRhLS1hLWNyaXRpY2FsbHktZW5kYW5nZXJlZC1saXZlcndvcnQtcmVjb3JkZWQvMTAuMjUyMjcvbGluYmcuMDEwNDkuZnVsbA&ntb=1' target='_blank'>Know More</a></p></div>";
              
            case "Brazil":
                return "<div><strong>Arthrocereus rondonianus</strong></div><div><img src='brazil.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Arthrocereus rondonianus is a species of cactus native to Brazil, specifically found in the state of Rondônia in the western part of the country. This cactus belongs to the genus Arthrocereus, which is known for its columnar growth habit and distinctive ribbed stems.</p><p>Arthrocereus rondonianus typically grows in dry, rocky habitats, often in association with other cactus species and succulent plants. It is adapted to withstand periods of drought and has specialized features, such as thick stems and reduced leaves, to conserve water.</p><p>Conservation efforts in Brazil aim to protect the natural habitats of Arthrocereus rondonianus and other native plant species. This includes establishing protected areas, enforcing regulations against illegal harvesting and habitat destruction, and promoting sustainable land management practices to preserve the country's rich biodiversity.</p><p><a href='https://www.bing.com/ck/a?!&&p=8a67dd0db1c830dcJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTI4Nw&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=arthrocereus+rondonianus&u=a1aHR0cHM6Ly9zdWNjdWxlbnRzbmV0d29yay5jb20vYXJ0aHJvY2VyZXVzLXJvbmRvbmlhbnVzLWd1aWRlLXdpdGgtcGljdHVyZXMv&ntb=1' target='_blank'>Know More</a></p></div>";
            case "Bulgaria":
                return "<div><strong></strong></div><div><img src='.jpg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p></p><p></p><p></p><p><a href='link' target='_blank'>Know More</a></p></div>";
            case "Colombia":
                return "<div><strong>Dipterocarpus turbinatus</strong></div><div><img src='cambodia.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Dipterocarpus turbinatus is a species of hardwood tree belonging to the genus Dipterocarpus, which is known for its valuable timber. However, it is important to note that Dipterocarpus turbinatus is not native to Colombia. Instead, it is primarily found in Southeast Asia, particularly in countries like India, Bangladesh, Myanmar, Thailand, and Laos.</p><p>In its native range, Dipterocarpus turbinatus plays a significant ecological role in tropical forests, providing habitat for various wildlife species and contributing to forest ecosystem functions such as nutrient cycling and soil stability.</p><p>Efforts to conserve Dipterocarpus turbinatus and other Dipterocarpus species include establishing protected areas, promoting sustainable forest management practices, and raising awareness about the importance of preserving tropical forests and their biodiversity. While this species may not be found in Colombia, similar conservation efforts are crucial in regions where Dipterocarpus turbinatus is native to ensure its long-term survival.</p><p><a href='https://www.bing.com/ck/a?!&&p=d67fc82ad8d86e5dJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTQ0MA&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=dipterocarpus+turbinatus&u=a1aHR0cHM6Ly93d3cubmF0dXJlLmNvbS9hcnRpY2xlcy9zNDE1OTgtMDE5LTQ4MjQwLXk&ntb=1' target='_blank'>Know More</a></p></div>";
            case "Canada":
                return "<div><strong>Whitebark pine (Pinus albicaulis)</strong></div><div><img src='canada.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Whitebark pine (Pinus albicaulis) is a species of pine tree native to the high-elevation mountainous regions of western North America, including parts of Canada such as British Columbia and Alberta. It is particularly prominent in the Rocky Mountains and the Pacific Northwest.</p><p>This tree species is well adapted to harsh mountain environments, often growing in rocky, subalpine areas with poor soils and extreme weather conditions. Whitebark pine is characterized by its distinctive white or light-colored bark and its large, resinous cones.</p><p>Whitebark pine plays a crucial ecological role in its habitat, serving as an important food source for various wildlife species, including grizzly bears, Clark's nutcrackers, and red squirrels. The seeds of the whitebark pine are high in fat and are an essential food source for many animals, especially during the winter months when other food sources are scarce.</p><p><a href='https://www.bing.com/ck/a?!&&p=22339345ba6e440eJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTI0Ng&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=whitebark+pine&u=a1aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvUGludXNfYWxiaWNhdWxpcw&ntb=1' target='_blank'>Know More</a></p></div>";
            case "Central African Republic":
                return"<div><strong>African mahogany</strong></div><div><img src='centralafricanrepublic.JPG' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>African mahogany, scientifically known as Khaya spp., is a group of tree species native to the tropical regions of Africa, including countries like the Central African Republic (CAR). While there are several species within the Khaya genus, the most commonly referred to as African mahogany include Khaya ivorensis and Khaya senegalensis.</p><p>These trees are valued for their high-quality timber, which is prized for its durability, attractive grain patterns, and ease of working. African mahogany wood is used in a variety of applications, including furniture making, cabinetry, flooring, and boat building.</p><p>In the Central African Republic, African mahogany trees can be found in the dense tropical forests that cover much of the country. These forests are home to a diverse array of plant and animal species, and they play a crucial role in maintaining local and regional biodiversity.</p><p><a href='https://www.bing.com/ck/a?!&&p=a0d5214260bb770dJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTI0Mg&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=african+mahogany+plant&u=a1aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvS2hheWE&ntb=1' target='_blank'>Know More</a></p></div>";
            
            case "China":
                return "<div><strong>Abies fanjingshanensis</strong></div><div><img src='china.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Abies fanjingshanensis is a species of fir tree native to China. Specifically, it is found in the Mount Fanjing (Fanjingshan) Nature Reserve in Guizhou Province, southwestern China. This reserve is a UNESCO World Heritage Site and a biodiversity hotspot, known for its unique and diverse flora and fauna.</p><p>Abies fanjingshanensis is a relatively recent discovery, having been identified as a distinct species in 1999. It is a coniferous tree that typically grows at high elevations in the mountainous regions of the reserve. The species is characterized by its tall stature, pyramidal shape, and dark green needles.</p><p>As an endemic species found only in a limited geographic area, Abies fanjingshanensis is of particular importance for conservation. It contributes to the ecological balance of its habitat and provides habitat for various wildlife species.</p><p><a href='https://www.bing.com/ck/a?!&&p=54c853d959b5d7feJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTIzOQ&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=abies+fanjingshanensis&u=a1aHR0cHM6Ly90aHJlYXRlbmVkY29uaWZlcnMucmJnZS5vcmcudWsvY29uaWZlcnMvYWJpZXMtZmFuamluZ3NoYW5lbnNpcw&ntb=1' target='_blank'>Know More</a></p></div>";
            
            case "Cuba":
                return "<div><strong>Annona ekmanii</strong></div><div><img src='cuba.jpg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Annona ekmanii is a species of flowering plant in the Annonaceae family, which is native to Cuba. It is commonly known as 'Chirimoya del Yunque' or 'Yunque Cherimoya' in Spanish. This species of Annona is endemic to the island nation, meaning it is found naturally only in Cuba.</p><p>Annona ekmanii is a small to medium-sized tree that typically grows in tropical and subtropical forests, particularly in regions with limestone soils. It is characterized by its glossy, dark green leaves and its fruits, which are similar in appearance to other members of the Annona genus, such as cherimoya and soursop.</p><p>The fruits of Annona ekmanii are edible and are consumed locally in Cuba. They have a sweet and aromatic flavor, making them popular for fresh consumption or for use in desserts and beverages.</p><p><a href='https://www.bing.com/ck/a?!&&p=80af2b469f0445a7JmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTI0MA&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=annona+ekmanii&u=a1aHR0cHM6Ly93d3cuc2VsaW5hd2FtdWNpaS5jb20vcGxhbnRzL2Fubm9uYWNlYWUvYW5ub25hLWVrbWFuaWkv&ntb=1' target='_blank'>Know More</a></p></div>";
            case "Denmark":
                return "<div><strong>Betula oycoviensis</strong></div><div><img src='denmark.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Betula oycoviensis, commonly known as the Oycov birch, is a species of birch tree native to Denmark and other parts of northern Europe. This birch species is known for its slender, erect growth habit and its distinctive bark, which is often white or silvery-gray in color with dark horizontal markings.</p><p>In Denmark, Betula oycoviensis is typically found in forests, woodlands, and other natural habitats with moist, well-drained soils. It is an important component of the country's native flora, contributing to the biodiversity and ecological balance of Danish ecosystems.</p><p>The wood of Betula oycoviensis is valued for its strength and durability, and it has been traditionally used in various applications, including furniture making, construction, and fuelwood. Additionally, birch trees, including Betula oycoviensis, have cultural significance and are sometimes planted for ornamental purposes in parks, gardens, and urban landscapes.</p><p><a href='https://www.bing.com/ck/a?!&&p=9600e4d6afc00fc9JmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTIyOA&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=betula+oycoviensis&u=a1aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvQmV0dWxhX3BlbmR1bGE&ntb=1' target='_blank'>Know More</a></p></div>";
            
            
           
            case "France":
                return "<div><strong>Limonium strictissimum</strong></div><div><img src='france.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Limonium strictissimum is a species of plant belonging to the family Plumbaginaceae. It is commonly known as strict sea lavender or narrow-leaved sea lavender. While it is not native to France, it is found in various parts of Europe, including coastal regions, salt marshes, and other saline habitats.</p><p>In France, Limonium strictissimum may be found along the coastlines of the Mediterranean Sea and the Atlantic Ocean, particularly in regions with sandy or rocky soils. It is known for its clusters of small, lavender-colored flowers that bloom in summer, adding color to coastal landscapes.</p><p>Strict sea lavender plays a role in stabilizing coastal ecosystems and providing habitat for insects and other wildlife. Additionally, it is sometimes used in coastal restoration projects to help prevent erosion and maintain biodiversity in fragile coastal habitats.</p><p><a href='https://www.bing.com/ck/a?!&&p=c9ca400441709559JmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTI3MQ&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=limonium+strictissimum&u=a1aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvTGltb25pdW0&ntb=1' target='_blank'>Know More</a></p></div>";
            
            case "Germany":
                return"<div><strong>Sorbus subcordata</strong></div><div><img src='germany.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Sorbus subcordata, commonly known as Caucasian whitebeam, is a species of tree native to the Caucasus region in Eurasia. It is not native to Germany. However, it is occasionally cultivated in botanical gardens, arboretums, and private gardens in Germany and other parts of Europe as an ornamental tree.</p><p>Caucasian whitebeam is known for its attractive foliage, which typically turns vibrant shades of orange, red, and purple in the autumn, adding color to the landscape. It also produces clusters of white flowers in the spring, followed by small, red or orange fruits that are attractive to birds.</p><p>While not native to Germany, Caucasian whitebeam may be appreciated for its ornamental value and ability to thrive in a variety of soil types and growing conditions. It may be planted in parks, gardens, and urban green spaces to provide shade, beauty, and habitat for wildlife.</p><p><a href='https://www.bing.com/ck/a?!&&p=39fe8e92919e112fJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTIzNg&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=sorbus+subcordata&u=a1aHR0cHM6Ly93d3cuc2VsaW5hd2FtdWNpaS5jb20vcGxhbnRzL3Jvc2FjZWFlL3NvcmJ1cy1zdWJjb3JkYXRhLw&ntb=1' target='_blank'>Know More</a></p></div>";
            case "Greece":
                return"<div><strong>Stonecress plant</strong></div><div><img src='greece.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Aurinia saxatilis is a low-growing perennial plant native to southeastern Europe, including Greece. It is characterized by its dense clusters of bright yellow flowers that bloom in early spring, creating a carpet of color in rocky or gravelly areas. The plant has gray-green foliage and a spreading growth habit, making it well-suited for rock gardens, slopes, and other sunny, well-drained locations.</p><p>In Greece, Aurinia saxatilis may be found growing in natural habitats such as mountainous regions, rocky slopes, and coastal cliffs. It is also cultivated as an ornamental plant in gardens and landscapes for its attractive flowers and ability to tolerate dry, poor soils.</p><p>As with many native plant species, conservation efforts in Greece aim to protect the natural habitats where stonecress plants grow and to promote their conservation in cultivation. This includes initiatives to preserve biodiversity, prevent habitat destruction, and raise awareness about the importance of native flora in maintaining healthy ecosystems.</p><p><a href='https://www.bing.com/ck/a?!&&p=79dc216e44ba4b69JmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTI2Ng&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=stonecress+plant&u=a1aHR0cHM6Ly93d3cuYnJpdGFubmljYS5jb20vcGxhbnQvc3RvbmVjcmVzcw&ntb=1' target='_blank'>Know More</a></p></div>";
            case "India":
                return"<div><strong>Berberis nilghiriensis</strong></div><div><img src='india.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Berberis nilghiriensis is a species of flowering plant belonging to the Berberidaceae family. It is commonly known as Nilgiri barberry. As the name suggests, it is native to the Nilgiri Hills in southern India, particularly in the states of Tamil Nadu and Kerala.</p><p>Nilgiri barberry is a small to medium-sized evergreen shrub characterized by its spiny branches and clusters of bright yellow flowers. It typically grows in the understory of forests, as well as in grasslands and rocky slopes, at elevations ranging from 1,000 to 2,500 meters above sea level.</p><p>Despite its local importance, Nilgiri barberry, like many other plant species, faces threats from habitat loss, deforestation, and overgrazing. Conservation efforts in India aim to protect the remaining populations of this species and their habitats through measures such as habitat restoration, protected area designation, and sustainable land management practices. Additionally, research is ongoing to better understand the ecology and conservation needs of Nilgiri barberry and other plant species endemic to the region.</p><p><a href='https://www.bing.com/ck/a?!&&p=992f2ee10330ae63JmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTI3MQ&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=berberis+nilghiriensis&u=a1aHR0cHM6Ly93d3cuc2VsaW5hd2FtdWNpaS5jb20vcGxhbnRzL2JlcmJlcmlkYWNlYWUvYmVyYmVyaXMtbmlsZ2hpcmllbnNpcy8&ntb=1' target='_blank'>Know More</a></p></div>";
            case "Indonesia":
                    return"<div><strong>Aglaia ceramica</strong></div><div><img src='indonesia.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Aglaia ceramica is a species of plant belonging to the Meliaceae family, commonly known as the soap tree family. It is native to Indonesia, particularly found in the Maluku Islands, also known as the Moluccas.</p><p>Aglaia ceramica is a tropical tree species that typically grows in lowland rainforests and tropical moist forests. It is characterized by its evergreen foliage and small, fragrant flowers. The tree produces fruits that contain seeds embedded in a fleshy pulp.</p><p>In Indonesia, Aglaia ceramica has several uses and cultural significance. Historically, various parts of the plant have been used for traditional medicine by indigenous communities. Additionally, the wood of Aglaia ceramica may be used for construction, furniture making, and other woodworking purposes.</p><p><a href='https://www.bing.com/ck/a?!&&p=5a9537c572022d56JmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTI3MQ&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=aglaia+ceramica&u=a1aHR0cHM6Ly93d3cuc2VsaW5hd2FtdWNpaS5jb20vcGxhbnRzL21lbGlhY2VhZS9hZ2xhaWEtY2VyYW1pY2Ev&ntb=1' target='_blank'>Know More</a></p></div>";
            case "Iran":
                return "<div><strong>Populus pruinose</strong></div><div><img src='iran.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Populus pruinosa is a species of tree commonly known as the white poplar or frost poplar. While it is native to regions of Central Asia, including Iran, it is not a widely known or extensively studied species.</p><p>The white poplar is a deciduous tree that typically grows in riparian habitats, along riverbanks, and in other moist environments. It is characterized by its grayish-white bark, especially noticeable on younger branches, and its ovate to triangular-shaped leaves with serrated edges. </p><p>In Iran, Populus pruinosa may be found in various provinces, particularly those with suitable habitats such as Gilan, Mazandaran, and Golestan. Like other poplar species, it may have cultural and ecological significance, providing habitat for wildlife, stabilizing soil along waterways, and contributing to local biodiversity.</p><p><a href='https://www.bing.com/ck/a?!&&p=3e135197130b91b2JmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTI0NQ&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=populus+pruinosa&u=a1aHR0cHM6Ly9hY2FkZW1pYy5vdXAuY29tL2hyL2FkdmFuY2UtYXJ0aWNsZS9kb2kvMTAuMTA5My9oci91aGFlMDM0Lzc2MDE3MTE&ntb=1' target='_blank'>Know More</a></p></div>";
    
            
            case "Ireland":
                return "<div><strong>Sorbus angilica</strong></div><div><img src='ireland.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Sorbus anglica, commonly known as the English whitebeam, is a species of flowering tree native to the British Isles, including Ireland. It belongs to the Rosaceae family and is closely related to other members of the Sorbus genus, such as rowans and mountain ashes.</p><p>The English whitebeam is a deciduous tree known for its distinctive foliage, which turns vibrant shades of red and orange in the autumn. It produces clusters of white flowers in the spring, followed by small red or orange berries that are attractive to birds and other wildlife.</p><p>n Ireland, Sorbus anglica can be found growing in various habitats, including woodlands, hedgerows, and scrublands. It plays a role in supporting local biodiversity, providing food and shelter for birds, insects, and other wildlife.</p><p><a href='https://www.bing.com/ck/a?!&&p=0aa70c7003a388ccJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTIzOQ&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=sprbus+angilica&u=a1aHR0cHM6Ly93d3cuc2VsaW5hd2FtdWNpaS5jb20vcGxhbnRzL3Jvc2FjZWFlL3NvcmJ1cy1hbmdsaWNhLw&ntb=1' target='_blank'>Know More</a></p></div>";
            case "Italy":
                return "<div><strong>Polygala vulgaris</strong></div><div><img src='italy.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Polygala vulgaris is a small herbaceous plant native to Europe, including Italy. It is characterized by its clusters of small, purplish-blue flowers that bloom in the spring and summer. The plant typically grows in grasslands, meadows, and open woodlands, often in nutrient-poor soils.</p><p>The common milkwort has traditional medicinal uses and has been historically used in herbal remedies for various ailments. However, it is primarily valued for its ornamental value and its role in supporting pollinators and other wildlife.</p><p>Conservation efforts in Italy aim to protect and preserve native plant species like Polygala vulgaris, as well as their habitats. This includes initiatives to prevent habitat destruction, promote sustainable land management practices, and raise awareness about the importance of biodiversity conservation.</p><p><a href='https://www.bing.com/ck/a?!&&p=79cb898e2a900966JmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTI0OA&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=milkwort&u=a1aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvUG9seWdhbGFfdnVsZ2FyaXM&ntb=1' target='_blank'>Know More</a></p></div>";
            case "Japan":
                return "<div><strong>Japanese bush spruce</strong></div><div><img src='japan.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>The Japanese bush spruce is a common name for Picea maximowiczii, a species of spruce native to Japan. It is also known as the Japanese spruce or Maximowicz's spruce. This tree species belongs to the Pinaceae family and is typically found in mountainous regions of Japan, including Honshu, Shikoku, and Kyushu islands.</p><p>Picea maximowiczii is a medium-sized evergreen tree characterized by its conical shape, dense foliage, and slender, drooping branches. The needles are dark green and arranged spirally around the branches. It produces small, cylindrical cones that mature from green to brown.</p><p>In Japan, Picea maximowiczii is valued for its timber, which is used in construction, furniture making, and paper production. It is also planted ornamentally in parks and gardens for its attractive appearance and ability to thrive in temperate climates.</p><p><a href='https://www.bing.com/ck/a?!&&p=0107f33bfd98e27bJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTI1Nw&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=japanese+bush+spruce&u=a1aHR0cHM6Ly93d3cudHJlZXNhbmRzaHJ1YnNvbmxpbmUub3JnL2FydGljbGVzL3BpY2VhL3BpY2VhLW1heGltb3dpY3ppaS8&ntb=1' target='_blank'>Know More</a></p></div>";
            
            case "Korea":
                return "<div><strong>Malus komarovii</strong></div><div><img src='korea.jpg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Malus komarovii, commonly known as Komarov's apple or Korean crabapple, is a species of flowering plant in the Rosaceae family. It is native to East Asia, particularly found in Korea, China, and Japan.</p><p>Komarov's apple is a small deciduous tree that typically grows in forests, woodlands, and mountainous regions. It is known for its beautiful springtime display of fragrant white or pink flowers, which attract pollinators such as bees and butterflies. The tree also produces small, tart fruits that are edible but are typically not consumed raw due to their sour taste. However, they can be used in preserves, jams, or for making alcoholic beverages.</p><p>In Korea, Malus komarovii has cultural significance and is sometimes planted for ornamental purposes in parks, gardens, and along roadsides. It is also valued for its ecological role in supporting biodiversity and providing habitat for wildlife.</p><p><a href='https://www.bing.com/ck/a?!&&p=998df4edd745abc4JmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTIzNA&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=malus+komarovii&u=a1aHR0cHM6Ly93d3cudHJlZXNhbmRzaHJ1YnNvbmxpbmUub3JnL2FydGljbGVzL21hbHVzL21hbHVzLWtvbWFyb3ZpaS8&ntb=1' target='_blank'>Know More</a></p></div>";
            
            case "Mexico":
                return "<div><strong>Acritodon nephophilus</strong></div><div><img src='mexico.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Acritodon nephophilus is a species of moss that is endemic to Mexico. Mosses are small, non-vascular plants that typically grow in moist environments, such as forests, streamsides, and rocky habitats.</p><p>As a moss species native to Mexico, Acritodon nephophilus likely contributes to the country's rich biodiversity and plays a role in local ecosystems. Mosses like Acritodon nephophilus help to stabilize soils, retain moisture, and provide habitat for a variety of microorganisms and small invertebrates.</p><p>Conservation efforts in Mexico aim to protect and preserve native plant species like Acritodon nephophilus and their habitats. This includes initiatives to prevent habitat destruction, promote sustainable land management practices, and raise awareness about the importance of preserving biodiversity.</p><p><a href='https://www.bing.com/ck/a?!&&p=6a23e7f5687e7265JmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTM1NQ&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=acritodon+nephophilus&u=a1aHR0cHM6Ly93d3cud2lraXdhbmQuY29tL2VuL0Fjcml0b2Rvbl9uZXBob3BoaWx1cw&ntb=1' target='_blank'>Know More</a></p></div>";
            case "Nepal":
                return "<div><strong>Diplocolea sikkimensis</strong></div><div><img src='nepal.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Diplocolea sikkimensis is a species of liverwort, a type of small, non-vascular plant, belonging to the family Diplocoleaceae. It is native to the Himalayan region, including Nepal, as well as parts of China and Bhutan.</p><p>As a liverwort species, Diplocolea sikkimensis typically grows in moist, shaded habitats, such as forests, rocky areas, and stream banks. It is characterized by its flattened, leaf-like structures called thalli, which often form dense mats on the substrate.</p><p>Liverworts like Diplocolea sikkimensis play important ecological roles in their habitats, such as soil stabilization, nutrient cycling, and providing habitat for microorganisms and small invertebrates.</p><p><a href='https://www.bing.com/ck/a?!&&p=d5e5700242a974c5JmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTIwMg&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=diplocolea+sikkimensis&u=a1aHR0cHM6Ly93d3cuc2VsaW5hd2FtdWNpaS5jb20vcGxhbnRzL3NvbGVub3N0b21hdGFjZWFlL2RpcGxvY29sZWEtc2lra2ltZW5zaXMv&ntb=1' target='_blank'>Know More</a></p></div>";
            case "Pakistan":
                return "<div><strong>Rhamnella gilgitica</strong></div><div><img src='pakistan.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Rhamnella gilgitica, a tree species belonging to the family Rhamnaceae, is native to Asia and is known for its self-supporting growth form. This species has been categorized as vulnerable by the International Union for Conservation of Nature (IUCN), indicating that it faces a high risk of extinction in the wild. The vulnerability status underscores the importance of conservation efforts to safeguard its populations and habitats.</p><p>One of the distinguishing features of Rhamnella gilgitica is its fruit type, which consists of drupes. These fruits play a crucial role in the tree's reproductive cycle and may also serve as a food source for various wildlife species.</p><p>Given its vulnerable status and the threats it faces, conservation measures are essential to ensure the long-term survival of Rhamnella gilgitica. Efforts may include habitat protection, restoration initiatives, population monitoring, and community engagement to raise awareness about the importance of preserving this species and its ecosystem.</p><p><a href='https://www.bing.com/ck/a?!&&p=3c1495929f5e2e2dJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTIzNw&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=rhamnella+gilgitica&u=a1aHR0cHM6Ly93d3cuc2VsaW5hd2FtdWNpaS5jb20vcGxhbnRzL3JoYW1uYWNlYWUvcmhhbW5lbGxhLWdpbGdpdGljYS8&ntb=1' target='_blank'>Know More</a></p></div>";
            case "Portugal":
                return "<div><strong>Juniper trees (Juniperus spp.)</strong></div><div><img src='portugal.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Juniper trees (Juniperus spp.) are indeed found in Portugal, particularly in regions with suitable habitats such as coastal areas, mountainous regions, and inland forests. The most common species of juniper found in Portugal is the Juniperus communis, also known as common juniper.</p><p>Juniper trees are evergreen conifers characterized by their needle-like leaves and small, berry-like cones. They are typically slow-growing and can vary in size from low shrubs to medium-sized trees, depending on the species and environmental conditions.</p><p>In Portugal, juniper trees may play various ecological roles, including providing habitat and food for wildlife, stabilizing soils, and contributing to the overall biodiversity of natural ecosystems. They are also valued for their aromatic wood and the berries, which are sometimes used in culinary applications and for making gin.</p><p><a href='https://www.bing.com/ck/a?!&&p=e3c99614f85dabaeJmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTYwMQ&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=juniper+trees&u=a1aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvSnVuaXBlcg&ntb=1' target='_blank'>Know More</a></p></div>";
            case "Russian ":
                return "<div><strong> Scapania spharifera</strong></div><div><img src='russia.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Scapania spharifera is a species of liverwort, a type of small, non-vascular plant, belonging to the family Scapaniaceae. Liverworts are commonly found in moist environments such as forests, bogs, and stream banks.</p><p>Scapania spharifera is native to Russia, particularly to regions with cool, humid climates such as boreal forests and mountainous areas. As a liverwort species, it typically grows in dense mats or patches on moist soil, rocks, or decaying wood.</p><p>Liverworts like Scapania spharifera play important ecological roles in their habitats, such as soil stabilization, nutrient cycling, and providing habitat for microorganisms and small invertebrates.</p><p><a href='https://www.bing.com/ck/a?!&&p=b2d8d99eb90c4a66JmltdHM9MTcwNzYwOTYwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTI0MA&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=scapania+spharifera&u=a1aHR0cHM6Ly93d3cuc2VsaW5hd2FtdWNpaS5jb20vcGxhbnRzL3NjYXBhbmlhY2VhZS9zY2FwYW5pYS1zcGhhZXJpZmVyYS8&ntb=1' target='_blank'>Know More</a></p></div>";
    
            case "South Africa":
                return "<div><strong></strong></div><div><img src='south africa.jpeg' alt='' style='float:right;width:200px;height:150px;margin-left:10px;'></div><div><p>Albizia suluensis, based on the description you provided, is a medium-sized tree with a rounded or spreading crown, typically reaching heights of 5-15 meters. The bark is gray, and the tree has a straight stem with thick, blunt-tipped branchlets.</p><p>The leaves of Albizia suluensis are compound, with a rachis (the central axis of a compound leaf) that can reach up to 80 mm in length. Each rachis bears 2-4 pairs of pinnae, which are smaller leaflet-bearing structures. Each pinnae typically bears 5-9 pairs of leaflets.</p><p></p><p><a href='https://www.bing.com/ck/a?!&&p=7189c29479936414JmltdHM9MTcwNzY5NjAwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTIxMg&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=albizia+suluensis&u=a1aHR0cDovL3B6YS5zYW5iaS5vcmcvYWxiaXppYS1zdWx1ZW5zaXM&ntb=1' target='_blank'>Know More</a></p></div>";
            case "Sri Lanka":
                return "<div><strong>Abarema bigemina</strong></div><div><img src='srilanka.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Abarema bigemina, commonly known as 'hora' in Sinhala, is a medium-sized tree that can reach heights of up to 15-20 meters. It is characterized by its spreading canopy and attractive, fern-like foliage.</p><p>The tree produces small, fragrant, creamy-white flowers that are arranged in dense clusters, adding to its ornamental value. These flowers attract pollinators such as bees and butterflies.</p><p>Abarema bigemina is also known for its large, flat seed pods, which contain seeds surrounded by a sweet, edible pulp. These pods are often consumed by local wildlife and are also used in traditional medicine in Sri Lanka.</p><p><a href='https://www.bing.com/ck/a?!&&p=9b8fe41dd8c6060dJmltdHM9MTcwNzY5NjAwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTIzOQ&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=abarema+bigemina&u=a1aHR0cHM6Ly93d3cuc2VsaW5hd2FtdWNpaS5jb20vcGxhbnRzL2ZhYmFjZWFlL2FyY2hpZGVuZHJvbi1iaWdlbWludW0v&ntb=1' target='_blank'>Know More</a></p></div>";
            
    
            case "Turkey":
                return "<div><strong>Pyrus serikensis</strong></div><div><img src='turkey.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Pyrus serikensis is a small to medium-sized deciduous tree belonging to the Rosaceae family. It is known for its rounded canopy and attractive foliage, making it a popular choice for ornamental planting in gardens and landscapes.</p><p>The tree produces white or pinkish flowers in the spring, followed by small, rounded fruits known as pears. These fruits are typically not as large or commercially significant as those of some other pear species but may still be consumed fresh or used in cooking and preserves.</p><p>Conservation efforts in Turkey aim to protect native tree species like Pyrus serikensis and their habitats. This includes initiatives to prevent habitat destruction, promote sustainable land management practices, and raise awareness about the importance of preserving biodiversity.</p><p><a href='https://www.bing.com/ck/a?!&&p=dd78b11ed2f03bd3JmltdHM9MTcwNzY5NjAwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTM1MA&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=pyrus+serikensis&u=a1aHR0cHM6Ly93d3cudGFuZGZvbmxpbmUuY29tL2RvaS9mdWxsLzEwLjEwODAvMTM4ODAyMDA2MDA1OTEyNTM&ntb=1' target='_blank'>Know More</a></p></div>";
    
            
            case "Zimbabwe":
                return "<div><strong>Bersama swynnertonii</strong></div><div><img src='zimbabwe.jpeg' alt='' style='float:right;width:200px;height:200px;margin-left:10px;'></div><div><p>Bersama swynnertonii, commonly known as the 'White ironwood' or 'Red ivory,'' is a medium to large-sized evergreen tree belonging to the Meliaceae family. It typically grows in woodland and forest habitats, particularly in regions with a subtropical or tropical climate.</p><p>This tree species is valued for its durable and dense wood, which is commonly used in carpentry, furniture making, and construction. The wood has a reddish-brown hue and is highly prized for its strength and resistance to decay.</p><p>Bersama swynnertonii produces small clusters of white or cream-colored flowers, which are followed by small, spherical fruits containing seeds. These fruits are an important food source for various wildlife species, including birds and mammals.</p><p><a href='lhttps://www.bing.com/ck/a?!&&p=d3b7c5af02933465JmltdHM9MTcwNzY5NjAwMCZpZ3VpZD0xYjY2ZGJiYi1hNTJlLTY1NmQtMDBkNC1jODU3YTQ3YzY0YjEmaW5zaWQ9NTIzMg&ptn=3&ver=2&hsh=3&fclid=1b66dbbb-a52e-656d-00d4-c857a47c64b1&psq=bersama+swynnertonii&u=a1aHR0cHM6Ly93d3cuc2VsaW5hd2FtdWNpaS5jb20vcGxhbnRzL2ZyYW5jb2FjZWFlL2JlcnNhbWEtc3d5bm5lcnRvbmlpLw&ntb=1' target='_blank'>Know More</a></p></div>";
    
    
            default:
                return "<p>No information available.</p>";
            }
        }
        
        
        
    });